### ISSUE TITLE
Class Fxp\Composer\AssetPlugin\Repository\NpmRepository does not exist 

### ISSUE THREAD

**Issue by dignityinside** [ElisDN/seokeys#3]
Composer вылетает с ошибкой:

```
Installation failed, deleting ./composer.json.

  [ReflectionException]                                                   
  Class Fxp\Composer\AssetPlugin\Repository\NpmRepository does not exist  

  [ErrorException]                                                             
  Declaration of Fxp\Composer\AssetPlugin\Repository\AbstractAssetsRepository  
  ::whatProvides() should be compatible with Composer\Repository\ComposerRepo  
  sitory::whatProvides(Composer\DependencyResolver\Pool $pool, $name, $bypass  
  Filters = false)  
```

Fix:

`composer global require "fxp/composer-asset-plugin:~1.1.1"`

**Comment by mfadel85** [comment]
it shows the same error when executing 
composer global require "fxp/composer-asset-plugin:~1.1.1"
![screenshot from 2016-04-18 12 39 45](https://cloud.githubusercontent.com/assets/612694/14599899/afc9952e-0562-11e6-953c-e8f1f910b3a2.png)

**Comment by ElisDN** [comment]
@dignityinside @Faddel Run `composer self-update`, remove `~/.composer/vendor/fxp` directory and install asset-plugin again.

**Comment by jonathasborges1** [comment]
funcionou vlw =)

**Comment by ravimisra** [comment]
Thanks! It worked!!

**Comment by xiaoxia2015** [comment]
Thanks! Very good!

**Comment by Suparuch** [comment]
don't work for me, how to fix it
